{{- if .Values.ingressRoute.enabled -}}
{{- $fullName := include "api.fullname" . -}}
{{- $dns := .Values.dns -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "api.name" . }}
    chart: {{ template "api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`api.{{ $dns }}`)
      services:
        - name: {{ $fullName }}
          port: {{ .Values.service.port }}
      middlewares:
        - name: cors-headers
        - name: security-headers
  tls:
    certResolver: le
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cors-headers
spec:
  headers:
    accessControlAllowMethods:
      - GET
      - POST
      - PUT
      - OPTIONS
      - PATCH
      - DELETE
      - HEAD
    accessControlAllowOriginList:
{{- range .Values.ingressRoute.allowedSubdomains }}
      - "https://{{ . }}.{{ $dns }}"
{{- end }}
    accessControlAllowHeaders:
      - Authorization
      - Origin
      - X-Requested-With
      - Content-Type
      - Accept
    accessControlExposeHeaders:
      - X-Total-Count
    accessControlMaxAge: {{ .Values.ingressRoute.maxAge }}
    addVaryHeader: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: security-headers
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    referrerPolicy: "origin"
    stsSeconds: 31536000
    stsIncludeSubdomains: true
    stsPreload: true
    forceSTSHeader: true
{{- end }}
