apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "api.fullname" . }}-migrate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  activeDeadlineSeconds: 3600
  template:
    metadata:
      labels:
        app: {{ template "api.name" . }}-migrate
        release: {{ .Release.Name }}
        env: {{ required "env is required" .Values.env }}
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}-sso-migrate
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          args:
            - sso-migrate
          env:
            - name: DSN_SSO
              valueFrom:
                secretKeyRef:
                  name: {{ template "api.name" . }}
                  key: dsn_sso
        - name: {{ .Chart.Name }}-box-migrate
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          args:
            - box-migrate
          env:
            - name: DSN_BOX
              valueFrom:
                secretKeyRef:
                  name: {{ template "api.name" . }}
                  key: dsn_box
      imagePullSecrets:
        - name: regcred
