.only-gateway:
  only:
    changes:
      - ".gitlab-ci.yml"
      - "gateway/**/*"

.except-wip-or-non-gateway-tags:
  except:
    variables:
      - $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /\+gateway$/
      - $CI_COMMIT_MESSAGE && $CI_COMMIT_MESSAGE =~ /^wip:/

# a gateway image is deployed on all branches
deploy_gateway_branch:
  stage: build
  extends:
    - .only-gateway
    - .only-branches-without-tags
    - .except-wip-or-non-gateway-tags
  image: docker:stable
  tags:
    - misakey_docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.misakey.dev
  script:
    - docker build -t $CI_REGISTRY_IMAGE/gateway:`if echo "$CI_COMMIT_REF_NAME" | grep -q "/"; then echo $CI_COMMIT_REF_NAME | sed -n "s/^.*\/\(.*\)$/\1/p"; else echo $CI_COMMIT_REF_NAME; fi` ./gateway
    - docker push $CI_REGISTRY_IMAGE/gateway:`if echo "$CI_COMMIT_REF_NAME" | grep -q "/"; then echo $CI_COMMIT_REF_NAME | sed -n "s/^.*\/\(.*\)$/\1/p"; else echo $CI_COMMIT_REF_NAME; fi`
