no-tests = true
no-hooks = true
pkgname = "sqlboiler"
output = "sqlboiler"
wipe = true

[psql]
  dbname = "api"
  host   = "localhost"
  port   = 5500
  user   = "misakey"
  pass   = "secret"
  sslmode = "disable"
  blacklist = ["goose_db_version"]
